.TH KARAT 1
.SH NAME
karat \- compile, lint, debug, and run Karat programs
.SH SYNOPSIS
.B karat
[\fB-l\fR]
[\fB-o\fR\fI FILE\fR]
[\fB-d\fR]
.IR file
.SH DESCRIPTION
.SH OPTIONS
.TP
.BR \-l
Check for parsing errors only
.TP
.BR \-d
After compiling, enter the debugger
.TP
.BR \-o " " \fIFILE\fR
Set the output file for compilation
