-- Generates all opcodes

-- maximum allowed opcodes
local MAX_OPCODES = 64

function opcode(name, number, mode)
    output(string.format("{ L\"%s\", %s, %s }, ", name, number, mode));
end

-- create indented output
local indent = 0
function output(str)
    print(string.rep("    ", indent) .. str)
end

-- print header
local time_table = os.date("*t", os.time())
print(string.format("/* Generated by OPGen, %s/%s/%s at %s:%s */",
                    time_table.month, time_table.day, time_table.year,
                    time_table.hour, time_table.min))
-- actual opcodes
local opcodes = {
    { "halt", "NO_MODE" },
    -- R opcodes
    { "adds",  "rmode(1, 1, 1, 0, 0)" }, -- signed add
    { "addu",  "rmode(1, 1, 1, 0, 0)" }, -- unsigned add
    { "xor",   "rmode(1, 1, 1, 0, 0)" }, -- xor two registers
    { "subs",  "rmode(1, 1, 1, 0, 0)" }, -- subtract two registers
    { "subu",  "rmode(1, 1, 1, 0, 0)" }, -- subtract two registers
    { "loadr", "rmode(1, 1, 0, 0, 0)" }, -- load register into register
    { "modr",  "rmode(1, 1, 1, 0, 0)" }, -- get remainder
    { "read",  "rmode(1, 0, 0, 0, 0)" }, -- read character from stdin
    -- I opcodes
    { "jmpr",  "imode(1, 0, 0)" }, -- jump relative to register
    { "addis", "imode(1, 1, 1)" }, -- immediate signed add */
    { "addiu", "imode(1, 1, 1)" }, -- immediate unsigned add */
    { "loadk", "imode(1, 0, 1)" }, -- load constant into register */
    { "putb",  "imode(1, 1, 1)" }, -- put byte */
    { "putw",  "imode(1, 1, 1)" }, -- put word */
    { "putl",  "imode(1, 1, 1)" }, -- put long */
    { "getb",  "imode(1, 1, 1)" }, -- get byte */
    { "getw",  "imode(1, 1, 1)" }, -- get word */
    { "getl",  "imode(1, 1, 1)" }, -- get long */
    { "putr",  "imode(1, 0, 0)" }, -- print register */
    { "putv",  "imode(0, 0, 1)" }, -- print value */
    { "beq",   "imode(1, 1, 1)" }, -- branch on equal */
    { "bne",   "imode(1, 1, 1)" }, -- branch on not equal */
    { "bgt",   "imode(1, 1, 1)" }, -- branch on not equal */
    { "blt",   "imode(1, 1, 1)" }, -- branch on not equal */
    -- B opcodes
    { "jmp",   "bmode(1)" },       -- jump */

}

if #opcodes >= MAX_OPCODES then
    print "more opcodes than allowed"
    return 1
end

output("#define MAX_OPCODES " .. MAX_OPCODES)

output "static const struct op_def op_defs[MAX_OPCODES] = {"

indent = indent + 1

for k, v in pairs(opcodes) do
    local def = string.format("%s_CODE", string.upper(v[1]))
    output(string.format("#define %s 0x%02X", def, k));
    opcode(v[1], def, v[2])
end

-- create sentinel value
output "{ NULL, 0, NO_MODE }, "

indent = indent - 1
output "};"
