#define MAX_OPCODES 64
enum {
    HALT_CODE = 0x00,
    NOP_CODE = 0x01,
    RET_CODE = 0x02,
    POPA_CODE = 0x03,
    PUSHA_CODE = 0x04,
    ADDS_CODE = 0x05,
    ADDU_CODE = 0x06,
    SUBS_CODE = 0x07,
    SUBU_CODE = 0x08,
    MULS_CODE = 0x09,
    MULU_CODE = 0x0A,
    DIVS_CODE = 0x0B,
    DIVU_CODE = 0x0C,
    XORR_CODE = 0x0D,
    COPY_CODE = 0x0E,
    MODR_CODE = 0x0F,
    PUSH_CODE = 0x10,
    PUSHB_CODE = 0x11,
    POP_CODE = 0x12,
    TRAP_CODE = 0x13,
    READ_CODE = 0x14,
    STOR_CODE = 0x15,
    INC_CODE = 0x16,
    DEC_CODE = 0x17,
    JMPR_CODE = 0x18,
    PUSHK_CODE = 0x19,
    ADDIS_CODE = 0x1A,
    ADDIU_CODE = 0x1B,
    SUBIS_CODE = 0x1C,
    SUBIU_CODE = 0x1D,
    LOADK_CODE = 0x1E,
    BEQ_CODE = 0x1F,
    BNE_CODE = 0x20,
    BGT_CODE = 0x21,
    BLT_CODE = 0x22,
    JMP_CODE = 0x23,
    CALL_CODE = 0x24,
};

static const struct op_def op_defs[MAX_OPCODES] = {
    { L"halt", HALT_CODE, NO_MODE }, 
    { L"nop", NOP_CODE, NO_MODE }, 
    { L"ret", RET_CODE, NO_MODE }, 
    { L"popa", POPA_CODE, NO_MODE }, 
    { L"pusha", PUSHA_CODE, NO_MODE }, 
    { L"adds", ADDS_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"addu", ADDU_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"subs", SUBS_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"subu", SUBU_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"muls", MULS_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"mulu", MULU_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"divs", DIVS_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"divu", DIVU_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"xorr", XORR_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"copy", COPY_CODE, rmode(1, 1, 0, 0, 0) }, 
    { L"modr", MODR_CODE, rmode(1, 1, 1, 0, 0) }, 
    { L"push", PUSH_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"pushb", PUSHB_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"pop", POP_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"trap", TRAP_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"read", READ_CODE, rmode(1, 1, 0, 0, 0) }, 
    { L"stor", STOR_CODE, rmode(1, 1, 0, 0, 0) }, 
    { L"inc", INC_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"dec", DEC_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"jmpr", JMPR_CODE, rmode(1, 0, 0, 0, 0) }, 
    { L"pushk", PUSHK_CODE, imode(0, 0, 1) }, 
    { L"addis", ADDIS_CODE, imode(1, 1, 1) }, 
    { L"addiu", ADDIU_CODE, imode(1, 1, 1) }, 
    { L"subis", SUBIS_CODE, imode(1, 1, 1) }, 
    { L"subiu", SUBIU_CODE, imode(1, 1, 1) }, 
    { L"loadk", LOADK_CODE, imode(1, 0, 1) }, 
    { L"beq", BEQ_CODE, bmode(1) }, 
    { L"bne", BNE_CODE, bmode(1) }, 
    { L"bgt", BGT_CODE, bmode(1) }, 
    { L"blt", BLT_CODE, bmode(1) }, 
    { L"jmp", JMP_CODE, bmode(1) }, 
    { L"call", CALL_CODE, bmode(1) }, 
    { NULL, 0, NO_MODE }, 
};
